- hosts: dns2
#- hosts: dns1ping
  become: yes
  tasks:
    - name: set Hostname
      shell:
        hostnamectl set-hostname rpdns2.mshome.loc

    - name: Copy IP setup for dns1
      copy: src=./rpdns1.dhcpcd.conf dest=/etc/dhcpcd.conf
      when: inventory_hostname == "dns1"

    - name: Copy IP setup for dns2
      copy: src=./rpdns2.dhcpcd.conf dest=/etc/dhcpcd.conf  
      when: inventory_hostname == "dns2"

    - name: Install dnsmasq, vim, dnsutils
      apt:
        state: latest
        update_cache: true
        pkg:
        - dnsmasq
        - vim
        - dnsutils
    - name: Copy dnsmasq.base for dns1
      copy:
         src: ./dnsmasq1.base
         dest: /etc/dnsmasq.base
      when: inventory_hostname == "dns1"

    - name: Copy dnsmasq.base for dns2
      copy:
         src: ./dnsmasq2.base
         dest: /etc/dnsmasq.base
      when: inventory_hostname == "dns2"

    - name: Copy dnsmasq.hosts
      copy:
         src: ./dnsmasq.hosts
         dest: ./etc/dnsmasq.hosts





    - name: Copy hosts
      copy:
         src: ./etchosts.new
         dest: /etc/hosts
    - name: Start dnsmasq
      service:
         name=dnsmasq
         state=started
         enabled=yes
#    - name: Add Resolv.conf entries
#      shell: |
#         nmcli connection modify 'Wired connection 1' ipv4.dns 127.0.0.1
#         nmcli connection modify 'Wired connection 1' ipv4.dns-options trust-ad
#         nmcli connection modify 'Wired connection 1' ipv4.ignore-auto-dns yes
#         nmcli connection modify 'Wired connection 1' ipv6.dns ::1
#         nmcli connection modify 'Wired connection 1' ipv6.dns-options trust-ad
#         nmcli connection modify 'Wired connection 1' ipv6.ignore-auto-dns yes     
#    - name: copy admin.conf to user's kube config
#      copy:
#        src: /etc/kubernetes/admin.conf
#        dest: /home/ubuntu/.kube/config
#        remote_src: yes
#        owner: ubuntu
#
#    - name: install Pod network
#      become: yes
#      become_user: ubuntu
#      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.log
#      args:
#        chdir: $HOME
#        creates: pod_network_setup.log
